#!/bin/bash

# source environment values
NAMESERVER4="10.3.3.24"
NAMESERVER6="2601:182:80:e752::3:4eb"
MESSAGE="{\"sourceId\":\"webosbrew\",\"message\":\"<b>Connman</b><br/>Poisoned connman lgtvonline.lge.com pings.\"}"

# Ensure that connman script runs only once per boot
once=/tmp/webosbrew_connman
exec 200>"${once}.lock"

if ! flock -x -n 200; then
  echo "[!] Connman script already running" >&2
  exit 1
fi

trap "rm -f ${once}.lock" EXIT

# poison lgtvonline.lge.com internet healthcheck
if [[ -e /var/luna/preferences/webosbrew_connman ]]; then
  echo >> /tmp/hosts
  echo "# dynamically added on boot by 00_connman script" >> /tmp/hosts
  echo "${NAMESERVER4} lgtvonline.lge.com" >> /tmp/hosts
  echo "${NAMESERVER6} lgtvonline.lge.com" >> /tmp/hosts
fi

luna-send -a webosbrew -f -n 1 luna://com.webos.notification/createToast "${MESSAGE}"

