#!/bin/bash

# source environment values
NAMESERVER4="10.3.3.24"
NAMESERVER6="2601:182:80:e752::3:4eb"

# Ensure that date script runs only once per boot
function lock {
  once=$1
  exec 200>"${once}.lock"

  if ! flock -x -n 200; then
    exit 1
  fi

  trap "rm -f ${once}.lock" EXIT
}

function toast {
  luna-send -a webosbrew -f -n 1 luna://com.webos.notification/createToast "$1"
}

# set date/time
function datetime {
  if [[ -e /var/luna/preferences/webosbrew_date ]]; then
    DATETIME="$(curl --head --insecure 'https://google.com/' 2>/dev/null | grep -i '^date:' | sed 's/^[Dd]ate: //g')"
    DATETIME=$(date -d "$DATETIME" -D '%a, %d %b %Y %T %Z' +'%Y-%m-%d %H:%M:%S')
    date -s "$DATETIME"
  fi
}

if [[ -e /var/luna/preferences/webosbrew_date ]]; then
  lock /tmp/webosbrew_date

  datetime
  toast "{\"sourceId\":\"webosbrew\",\"message\":\"<b>LG TV Take Back Control</b><br/>Set current date/time.\"}"
fi
