#!/bin/bash

# source environment values
NAMESERVER4="10.3.3.24"
NAMESERVER6="2601:182:80:e752::3:4eb"

# Ensure that telemetry script runs only once per boot
function lock {
  once=$1
  exec 200>"${once}.lock"

  if ! flock -x -n 200; then
    exit 1
  fi

  trap "rm -f ${once}.lock" EXIT
}

function toast {
  luna-send -a webosbrew -f -n 1 luna://com.webos.notification/createToast "$1"
}

# Poison telemetry servers
function poison {
  if [[ -e /var/luna/preferences/webosbrew_telemetry ]]; then
    echo >> /tmp/hosts
    echo "# dynamically added on boot by 02_telemetry script" >> /tmp/hosts
    echo "127.0.01 api.thetake.com discovery.meethue.com www.ueiwsp.com mediaservices.cdn-apple.com ocsp.apple.com" >> /tmp/hosts
    echo "::1 api.thetake.com discovery.meethue.com www.ueiwsp.com mediaservices.cdn-apple.com ocsp.apple.com" >> /tmp/hosts
  fi
}

if [[ -e /var/luna/preferences/webosbrew_telemetry ]]; then
  lock /tmp/webosbrew_telemetry
  poison
  toast "{\"sourceId\":\"webosbrew\",\"message\":\"<b>Poisoned telemetry DNS</b><br/>Poisoned telemetry domains in /etc/hosts.\"}"
fi
