#!/bin/bash

# source environment values
NAMESERVER4="10.3.3.24"
NAMESERVER6="2601:182:80:e752::3:4eb"
OVERLAY_BASE=/var/lib/webosbrew/ca

# Ensure that lgtv_tbc script runs only once per boot
function lock {
  once=$1
  exec 200>"${once}.lock"

  if ! flock -x -n 200; then
    exit 1
  fi

  trap "rm -f ${once}.lock" EXIT
}

function toast {
  luna-send -a webosbrew -f -n 1 luna://com.webos.notification/createToast "$1"
}

function overlay {
    set -e
    overlay_id="$(echo $1 | sed 's;/;__;g')"
    unset TARGET SOURCE FSTYPE OPTIONS
    eval $(findmnt -P $1)
    if [[ "$FSTYPE" == "overlay" ]] || [ -f "$1" ] && [[ "$FSTYPE" != "" ]]; then
        echo "Overlay '$1' already mounted"
    elif [ -f "$1" ]; then
        if [ ! -f "$OVERLAY_BASE/$overlay_id" ]; then
            cp $1 $OVERLAY_BASE/$overlay_id;
        fi
        mount --bind "$OVERLAY_BASE/$overlay_id" "$1"
    else
        mkdir -p "$OVERLAY_BASE/$overlay_id/upper" "$OVERLAY_BASE/$overlay_id/work"
        mount -t overlay -o lowerdir=$1,upperdir=$OVERLAY_BASE/$overlay_id/upper/,workdir=$OVERLAY_BASE/$overlay_id/work/ overlay-$overlay_id $1
    fi
}

function c_rehash {
  (
    cd /etc/ssl/certs
    for file in *.pem; do
      HASH=$(openssl x509 -hash -noout -in "$file")
      if [ ! -e "${HASH}.0" ]; then
        ln -s "$file" "${HASH}.0"
      fi
    done
  )
}

function root {
  if [ ! -f "/usr/share/ca-certificates/mozilla/LG_TV_TakeBackControl_Root.crt" ]; then
    cat << EOF > /usr/share/ca-certificates/mozilla/LG_TV_TakeBackControl_Root.crt
# LG_TV_TakeBackControl_Root.crt
-----BEGIN CERTIFICATE-----
MIIFYTCCA0mgAwIBAgIBATANBgkqhkiG9w0BAQsFADA7MQswCQYDVQQGEwJVUzER
MA8GA1UECgwIbGd0di10YmMxGTAXBgNVBAMMEGxndHYtdGJjIHJvb3QgQ0EwIBcN
MjIxMDI4MjMwNTA4WhgPMjEyMjEwMDQyMzA1MDhaMEMxCzAJBgNVBAYTAlVTMREw
DwYDVQQKDAhsZ3R2LXRiYzEhMB8GA1UEAwwYbGd0di10YmMgaW50ZXJtZWRpYXRl
IENBMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAuSQHaqwy6mhPpAEV
/8TcaXNimOoetoNG04q1yvi5TcMSWgMk8keLi5e82YvgLyYsKUhKSODcS2y9VStz
56jgMVAXwWMtdo1HNSPc+63rcHn/p2qGVNajDwirQqDiYwIEl/4yUyKIkKjqvNU9
0UgrNrssuFFQT13WMT6L5pxpDZrCSd+c2VQn6vw2uJAcR8iEBP7oDVFPHTmMx4BQ
3IXYQQuWw0HSH/WsN5eyJ5Me3NY4QtgVT5GMWOEPzywuMbIu3CdCJVfF6kT1DVO7
0pGd6aRXwy2+0PGfxgm8vSp6bBNYJa4sRxC64XFF5t5P9CGTGSVHQvr1m21NbGLm
2M5xRm80uANqvm7nFVElKvV6Q/BJKty/zw97QLLHSxF8ggy1bc3uJB6qP71PC7HU
n8QKnpbvNBh7wqY7nS1LfdRUsILJxXokwrM1aOsURP50Y4ScMpr+9+ERpA7l9Zy9
yjWfiAUHHPgpu8RcsDa8txZs1RBpFUwwbNTxl1FdR/y+WuYo98/TpsRhZA+JJkia
m5xBH9Xe/SQww85d9nKAYjZ5luuivJPE03H5X9lQegD/TP/nFsy9Kmh580Kl6X3g
lW/lyvgfM5ZyrAqCqnLIvSnAE04em0zV1Ea3uaHv5CAaYb4YvQ3Pn9L984to+Kz3
Npb3dHpJK14rqo6ITlERw8vlbBUCAwEAAaNmMGQwHQYDVR0OBBYEFGs7aCavDl6r
yiw/4ySt429wPuYWMB8GA1UdIwQYMBaAFNsAi/FCdnE/reMi88BJ88xnHejLMBIG
A1UdEwEB/wQIMAYBAf8CAQAwDgYDVR0PAQH/BAQDAgGGMA0GCSqGSIb3DQEBCwUA
A4ICAQAmDlJ7zfwQtmuobMQ29UBerimOmOIkQLbc0lQsdiOdQ29SjgOq1l8gQdPk
Uto0dZ9BdoerTmJAmgHK0BZdSdUngrxwcV1EO0fJcJ5Ux8YgTRpuzExGf0bqUZh2
RSX2MN/bodPRLAHNdxiL2ozOrPw3JDgZR0Eo8bTkE+zj+DsOxNwfMTt6sKBVNx1Q
8M/ER1566DgoUTlVSkJGrAtbIi/jIbYnmBaxl/ftg7zinOQyarWLSU8K3/uVrhxB
hO0E4EcWrR+E9DnbN0k+6TTu7QZO6rXmvxhmCvt5ii+lXL7rgMkakeUIVHDUB9RX
8ouYelHYg1XBzt9Jd1DpowCKyiNTByl9sr26pQRkLraWUp0MR4fYP8Vsv57VtdVV
pOaPO/FnuLmlpTGlx/xtQcWLsMy+eu8EoobzE0hRRDBnEd99AXzn4zuw2yhN4TGQ
d3Em06pld3j88kJ/AzPqjCGPiqow1p71KkSsEg+epqZEgKRcG3XfM7tCErU5p1Mc
ecl+uivgQNnIh4jSBTbbn7FwMCt8WBcFzLTmbpPR8JYiDoUsnUYiqamlVIYTCBVT
puLA/fv9C3BYCsjKE/KO/O16/4uw5U0nMqCp2HO8LK3WyIdLKogk9PpnP++/zTOj
vaZ1+6gM7FnfOcHxtxXt7O+NEF+BEup4HjDdW8TemoLgASDzLA==
-----END CERTIFICATE-----
EOF
  fi

  echo "mozilla/LG_TV_TakeBackControl_Root.crt" >> /etc/ca-certificates.conf
  sed -e '/^#/d' /usr/share/ca-certificates/mozilla/LG_TV_TakeBackControl_Root.crt > /etc/ssl/certs/trusted_ca56.pem
  cat /usr/share/ca-certificates/mozilla/LG_TV_TakeBackControl_Root.crt >> /etc/ssl/certs/trusted_cas.crt
  cat /usr/share/ca-certificates/mozilla/LG_TV_TakeBackControl_Root.crt >> /usr/share/ca-certificates/sdp/sdp-ca.pem
}

function intermediate {
  if [ ! -f "/usr/share/ca-certificates/mozilla/LG_TV_TakeBackControl_Intermediate.crt" ]; then
    cat << EOF > /usr/share/ca-certificates/mozilla/LG_TV_TakeBackControl_Intermediate.crt
# LG_TV_TakeBackControl_Intermediate.crt
-----BEGIN CERTIFICATE-----
MIIFaTCCA1GgAwIBAgIUFsso/p77JrGEFuboplmrawmhbJYwDQYJKoZIhvcNAQEL
BQAwOzELMAkGA1UEBhMCVVMxETAPBgNVBAoMCGxndHYtdGJjMRkwFwYDVQQDDBBs
Z3R2LXRiYyByb290IENBMCAXDTIyMTAyODIzMDQ1OFoYDzMwMjIwMjI4MjMwNDU4
WjA7MQswCQYDVQQGEwJVUzERMA8GA1UECgwIbGd0di10YmMxGTAXBgNVBAMMEGxn
dHYtdGJjIHJvb3QgQ0EwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQCt
dyvOa9wAvdbJKfdxvoCNnKDUKi4OLaeu5hGNf3+7cZ0ESZ6070qQE7rmoRGY+83T
raVH4YRecq9fv7LHVjhZtWseUW1fUJt8YXRhrA7sL3xi/mOSwNLrBTMX/NKAawE7
QGFeYZVwdDO9CB14rIO8yhzaeQ9kUDP179aec6s3jMPAO3GXWGoz6XFPstI9+DZt
bkhvV1trcoRaJ9o2oz3npquID51TkNTWMbiv2IJZ3/NXCERhQ0Uysjuyf98RyHOG
Xj2928NH/WS66zepYzR4lwf1uMM/98Ox1nhv1APn8AKfzvaVz4r0C7C1qUTBFNaK
sD4/1HD4XtM7IYJbH/YfVcPPOS0Y2X6N4kRaALLAs2Jg30MM0lUGHFCzFfh8IXPl
8WP1ybjoe5cMvcn7H5Jm/uK9iV8d3PyCcm2XZdMfPODsX7SvboLWDxyuVx4TWhHw
JESjjwdvlrgKFXFIraKkyBumkQ4rwp9wxCc30NKtjeIzMeo2qwa2TIRvKyk6CXtr
DRh0PtFo6fRdokq4tBMkN8JJv3HbrscmCLKuvODtXdpL1vRruDZIVy6LhXihcxnB
/TFu6RlZla/rBJJeTz4LxYKKSPGUcOVonDUAcAQzcxYpo5irqRD3H7wVxCZuHKPa
2kO/Z97Cgw29A9erNH3caGyZYjSK7O1pK3XQnYhgtQIDAQABo2MwYTAdBgNVHQ4E
FgQU2wCL8UJ2cT+t4yLzwEnzzGcd6MswHwYDVR0jBBgwFoAU2wCL8UJ2cT+t4yLz
wEnzzGcd6MswDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAYYwDQYJKoZI
hvcNAQELBQADggIBAAoZ79Og3bF+4tIITdNMALSFrdlJdjyQyKseto6ZTKU5RvTp
X7d4yDAGXWe6bNpDkQFkAfQtJWGzff9p0ECQZCvY9TZ/a9CFGLuOVPW+lmVgBvDy
PcFjhiNaTBcM6+bWH9xIItj2HEbPKCTSWiu/1w18+irx5D4XeJe3Nm7OpD4s0GrZ
GxXK62aL7Z+zebNv3rvMi719UWLATmauTukwoeeWYMzKwvX5WOgiEFbPxOx1/XHv
atZar2fSeoKn8yvIBFixV3TdSwpXrORWY97A7IGfRldFtQRZjlONpC0YGWS2wqDL
WBokHjJjuUkP3nlCcodPnkHfBLiYClGFFPZIeZhY5AxSboJJwjzwEKUr3/Gx4nwu
e2MDetAS9ew44iPQx1J23M6Ki/NODrTstchh1CQO70pasZRUv/5wvZ+Ul48D8ph6
CRFjpLRB80UoNYcJVZ24tsaJeVq9i5B53LgEOM0KCGTNGA7df7atkE8W1rGK1Xpw
3504XFodLeC/AFYrYH46ShtIicRO7LGDYEdAMqBYhY2Kg+pKakNv7GHN0Uv/76tO
0oHJCo9a38o3DKx+46KUkE2CSiISB6gwRLGmI2Ps0uzJNlUNwks2J4Av7nc2SxQM
6dHv9YbuDqSGA4TduX73r3AR6hrE5TY2jdHkUdyjX7pm7xw76odUyh9wze8i
-----END CERTIFICATE-----
EOF
  fi

  echo "mozilla/LG_TV_TakeBackControl_Intermediate.crt" >> /etc/ca-certificates.conf
  sed -e '/^#/d' /usr/share/ca-certificates/mozilla/LG_TV_TakeBackControl_Intermediate.crt > /etc/ssl/certs/trusted_ca57.pem
  cat /usr/share/ca-certificates/mozilla/LG_TV_TakeBackControl_Intermediate.crt >> /etc/ssl/certs/trusted_cas.crt
  cat /usr/share/ca-certificates/mozilla/LG_TV_TakeBackControl_Intermediate.crt >> /usr/share/ca-certificates/sdp/sdp-ca.pem
}

#cp /usr/share/ca-certificates/sdp/sdp-ca.pem /tmp/sdp-ca.pem
#cat << EOF >> /tmp/sdp-ca.pem
#cat << EOF >> /tmp/sdp-ca.pem
#mount --bind /tmp/sdp-ca.pem /usr/share/ca-certificates/sdp/sdp-ca.pem

if [[ -e /var/luna/preferences/webosbrew_lgtv_tbc ]]; then
  lock /tmp/webosbrew_lgtv_tbc
  overlay /etc/ssl/certs
  overlay /usr/share/ca-certificates
  overlay /etc/ca-certificates.conf

  root
  intermediate

  update-ca-certificates
  c_rehash

  toast "{\"sourceId\":\"webosbrew\",\"message\":\"<b>LG TV Take Back Control</b><br/>Poisoned SSL certificates added.\"}"
fi
