#!/bin/bash

# source environment values
NAMESERVER4="10.3.3.24"
NAMESERVER6="2601:182:80:e752::3:4eb"
OVERLAY_BASE=/var/lib/webosbrew/ca

# Ensure that lgtv_tbc script runs only once per boot
function lock {
  once=$1
  exec 200>"${once}.lock"

  if ! flock -x -n 200; then
    exit 1
  fi

  trap "rm -f ${once}.lock" EXIT
}

function toast {
  luna-send -a webosbrew -f -n 1 luna://com.webos.notification/createToast "$1"
}

function overlay {
    set -e
    overlay_id="$(echo $1 | sed 's;/;__;g')"
    unset TARGET SOURCE FSTYPE OPTIONS
    eval $(findmnt -P $1)
    if [[ "$FSTYPE" == "overlay" ]] || [ -f "$1" ] && [[ "$FSTYPE" != "" ]]; then
        echo "Overlay '$1' already mounted"
    elif [ -f "$1" ]; then
        if [ ! -f "$OVERLAY_BASE/$overlay_id" ]; then
            cp $1 $OVERLAY_BASE/$overlay_id;
        fi
        mount --bind "$OVERLAY_BASE/$overlay_id" "$1"
    else
        mkdir -p "$OVERLAY_BASE/$overlay_id/upper" "$OVERLAY_BASE/$overlay_id/work"
        mount -t overlay -o lowerdir=$1,upperdir=$OVERLAY_BASE/$overlay_id/upper/,workdir=$OVERLAY_BASE/$overlay_id/work/ overlay-$overlay_id $1
    fi
}

function c_rehash {
  (
    cd /etc/ssl/certs
    for file in *.pem; do
      HASH=$(openssl x509 -hash -noout -in "$file")
      if [ ! -e "${HASH}.0" ]; then
        ln -s "$file" "${HASH}.0"
      fi
    done
  )
}

function root {
  if [ ! -f "/usr/share/ca-certificates/mozilla/LG_TV_TakeBackControl_Root.crt" ]; then
    curl --fail --silent --show-error --location --output /usr/share/ca-certificates/mozilla/LG_TV_TakeBackControl_Root.crt https://raw.githubusercontent.com/rpinz/lgtv-tbc/master/ssl/build/LG_TV_TakeBackControl_Root.crt
  fi

  echo "mozilla/LG_TV_TakeBackControl_Root.crt" >> /etc/ca-certificates.conf
  openssl x509 -in /usr/share/ca-certificates/mozilla/LG_TV_TakeBackControl_Root.crt -out /etc/ssl/certs/trusted_ca56.pem
  cat /etc/ssl/certs/trusted_ca56.pem >> /etc/ssl/certs/trusted_cas.crt
  cat /etc/ssl/certs/trusted_ca56.pem >> /usr/share/ca-certificates/sdp/sdp-ca.pem
}

function intermediate {
  if [ ! -f "/usr/share/ca-certificates/mozilla/LG_TV_TakeBackControl_Intermediate.crt" ]; then
    curl --fail --silent --show-error --location --output /usr/share/ca-certificates/mozilla/LG_TV_TakeBackControl_Intermediate.crt https://raw.githubusercontent.com/rpinz/lgtv-tbc/master/ssl/build/LG_TV_TakeBackControl_Intermediate.crt
  fi

  echo "mozilla/LG_TV_TakeBackControl_Intermediate.crt" >> /etc/ca-certificates.conf
  openssl x509 -in /usr/share/ca-certificates/mozilla/LG_TV_TakeBackControl_Intermediate.crt -out /etc/ssl/certs/trusted_ca57.pem
  cat /etc/ssl/certs/trusted_ca57.pem >> /etc/ssl/certs/trusted_cas.crt
  cat /etc/ssl/certs/trusted_ca57.pem >> /usr/share/ca-certificates/sdp/sdp-ca.pem
}

#cp /usr/share/ca-certificates/sdp/sdp-ca.pem /tmp/sdp-ca.pem
#cat << EOF >> /tmp/sdp-ca.pem
#cat << EOF >> /tmp/sdp-ca.pem
#mount --bind /tmp/sdp-ca.pem /usr/share/ca-certificates/sdp/sdp-ca.pem

if [[ -e /var/luna/preferences/webosbrew_lgtv_tbc ]]; then
  lock /tmp/webosbrew_lgtv_tbc
  overlay /etc/ssl/certs
  overlay /usr/share/ca-certificates
  overlay /etc/ca-certificates.conf

  root
  intermediate

  update-ca-certificates
  c_rehash

  toast "{\"sourceId\":\"webosbrew\",\"message\":\"<b>LG TV Take Back Control</b><br/>Poisoned SSL certificates added.\"}"
fi
