#!/bin/bash

# source environment values
NAMESERVER4="10.3.3.24"
NAMESERVER6="2601:182:80:e752::3:4eb"
MESSAGE="{\"sourceId\":\"webosbrew\",\"message\":\"<b>DNS</b><br/>Poisoned DNS.\"}"

# Ensure that resolv script runs only once per boot
once=/tmp/webosbrew_resolv
exec 200>"${once}.lock"

if ! flock -x -n 200; then
  echo "[!] DNS script already running" >&2
  exit 1
fi

trap "rm -f ${once}.lock" EXIT

if [[ -e /var/luna/preferences/webosbrew_resolv ]]; then
  echo "# dynamically added on boot by 04_resolv script" > /tmp/resolv.conf
  echo "nameserver ${NAMESERVER4}" >> /tmp/resolv.conf
  echo "nameserver ${NAMESERVER6}" >> /tmp/resolv.conf
  mount --bind /tmp/resolv.conf /var/lib/misc/resolv.conf
fi

luna-send -a webosbrew -f -n 1 luna://com.webos.notification/createToast "${MESSAGE}"

